/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListViewPanel.java
 *
 * Created on Oct 20, 2009, 3:46:39 PM
 */

package de.sofd.viskit.test.singleframe;

import de.sofd.viskit.ui.imagelist.JImageListView;

/**
 *
 * @author olaf
 */
public class ListViewPanel extends javax.swing.JPanel {

    /** Creates new form ListViewPanel */
    public ListViewPanel() {
        initComponents();
    }

    public JImageListView getListView() {
        return listView;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        mouseWindowingController = new de.sofd.viskit.controllers.ImageListViewMouseWindowingController();
        scaleModesComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        listView = new de.sofd.viskit.ui.imagelist.jlistimpl.JListImageListView();

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listView, org.jdesktop.beansbinding.ObjectProperty.create(), mouseWindowingController, org.jdesktop.beansbinding.BeanProperty.create("controlledImageListView"));
        bindingGroup.addBinding(binding);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${supportedScaleModes}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listView, eLProperty, scaleModesComboBox);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel1.setText("Scale Mode:");

        listView.setBackground(new java.awt.Color(0, 0, 0));
        listView.setSelectionBackground(java.awt.Color.darkGray);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, scaleModesComboBox, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), listView, org.jdesktop.beansbinding.BeanProperty.create("scaleMode"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scaleModesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
            .addComponent(listView, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(scaleModesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(listView, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private de.sofd.viskit.ui.imagelist.jlistimpl.JListImageListView listView;
    private de.sofd.viskit.controllers.ImageListViewMouseWindowingController mouseWindowingController;
    private javax.swing.JComboBox scaleModesComboBox;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
