package de.sofd.viskit.ui;

import de.sofd.draw2d.viewer.tools.DrawingViewerTool;
import de.sofd.draw2d.viewer.tools.EllipseTool;
import de.sofd.draw2d.viewer.tools.PolygonTool;
import de.sofd.draw2d.viewer.tools.RectangleTool;
import de.sofd.draw2d.viewer.tools.SelectorTool;
import de.sofd.util.BiHashMap;
import de.sofd.util.BiMap;
import javax.swing.JToggleButton;
import org.apache.log4j.Logger;

/**
 *
 */
public class RoiToolPanel extends javax.swing.JPanel {

    private final BiMap<JToggleButton, Class<? extends DrawingViewerTool> > toolClassesByButton =
            new BiHashMap<JToggleButton, Class<? extends DrawingViewerTool> >();

    private Class<? extends DrawingViewerTool> toolClass;
    public static final String PROP_TOOLCLASS = "toolClass";

    /** Creates new form RoiJPanel */
    public RoiToolPanel() {
        initComponents();
        toolClassesByButton.put(selectorToggleButton, SelectorTool.class);
        toolClassesByButton.put(ellipseToggleButton, EllipseTool.class);
        toolClassesByButton.put(rectangleToggleButton, RectangleTool.class);
        toolClassesByButton.put(polygonToggleButton, PolygonTool.class);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roiButtonGroup = new javax.swing.ButtonGroup();
        selectorToggleButton = new javax.swing.JToggleButton();
        ellipseToggleButton = new javax.swing.JToggleButton();
        rectangleToggleButton = new javax.swing.JToggleButton();
        polygonToggleButton = new javax.swing.JToggleButton();

        roiButtonGroup.add(selectorToggleButton);
        selectorToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/sofd/viskit/ui/selector.png"))); // NOI18N
        selectorToggleButton.setSelected(true);
        selectorToggleButton.setToolTipText("Selector");
        selectorToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolButtonClicked(evt);
            }
        });

        roiButtonGroup.add(ellipseToggleButton);
        ellipseToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/sofd/viskit/ui/ellipse.png"))); // NOI18N
        ellipseToggleButton.setToolTipText("Ellipse");
        ellipseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolButtonClicked(evt);
            }
        });

        roiButtonGroup.add(rectangleToggleButton);
        rectangleToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/sofd/viskit/ui/rectangle.png"))); // NOI18N
        rectangleToggleButton.setToolTipText("Rectangle");
        rectangleToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolButtonClicked(evt);
            }
        });

        roiButtonGroup.add(polygonToggleButton);
        polygonToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/sofd/viskit/ui/polygon.png"))); // NOI18N
        polygonToggleButton.setToolTipText("Polygon");
        polygonToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(selectorToggleButton)
                .addComponent(ellipseToggleButton)
                .addComponent(rectangleToggleButton)
                .addComponent(polygonToggleButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectorToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ellipseToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rectangleToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(polygonToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toolButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolButtonClicked
        Class<? extends DrawingViewerTool> toolClass = toolClassesByButton.get(evt.getSource());
        setToolClass(toolClass);
}//GEN-LAST:event_toolButtonClicked

    /**
     * Get the value of toolClass
     *
     * @return the value of toolClass
     */
    public Class<? extends DrawingViewerTool> getToolClass() {
        return toolClass;
    }

    /**
     * Set the value of toolClass
     *
     * @param toolClass new value of toolClass
     */
    public void setToolClass(Class<? extends DrawingViewerTool> toolClass) {
        Class<? extends DrawingViewerTool> oldToolClass = this.toolClass;
        if (this.toolClass != toolClass) {
            JToggleButton button = toolClassesByButton.reverseGet(toolClass);
            button.setSelected(true);
            this.toolClass = toolClass;
            firePropertyChange(PROP_TOOLCLASS, oldToolClass, toolClass);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ellipseToggleButton;
    private javax.swing.JToggleButton polygonToggleButton;
    private javax.swing.JToggleButton rectangleToggleButton;
    private javax.swing.ButtonGroup roiButtonGroup;
    private javax.swing.JToggleButton selectorToggleButton;
    // End of variables declaration//GEN-END:variables

    static final Logger log4jLogger = Logger.getLogger(RoiToolPanel.class);
}
